name: Nightly

on:

  schedule:
    - cron: '0 3 * * *'
    
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: lint
        run: ./gradlew ktlintCheck

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Tests
      run: ./gradlew test

  assemble:
    runs-on: ubuntu-latest

    needs: [lint, test]

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: build 
      run: ./gradlew assembleDebug
