name: Quality Gate

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Tests
      run: ./gradlew test
            
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: lint
        run: ./gradlew ktlintCheck

  assemble:
    runs-on: ubuntu-latest

    needs: [test,lint]

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: build 
      run: ./gradlew assembleDebug
