name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
    
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.2
        with:
          configurationFile: renovate.json
          token: ${{ secrets.TOKEN }}
        env:
         LOG_LEVEL: 'debug'
